CREATE TABLE [Logging].[LogixLogException]
(
	[LogixLogExceptionID] INT NOT NULL PRIMARY KEY IDENTITY,
    [ApplicationName] VARCHAR(75) NULL, 
    [ConnectLoginID] VARCHAR(256) NULL, 
    [ErrorMessage] VARCHAR(500) NULL, 
    [StackTrace] VARCHAR(4000) NULL,
	[HelpLink] VARCHAR(1000) NULL,
	[HResult] INT NULL,
	[Source] VARCHAR(1000) NULL,
    [ClientIPAddress] VARCHAR(20) NULL, 
    [ClientMachine] VARCHAR(60) NULL, 
	[ClientOS] VARCHAR(100) NULL,
	[ClientBrowser] VARCHAR(100) NULL,
    [ApplicationPool] VARCHAR(75) NULL,
	[RequestType] VARCHAR(10) NULL,
	[LogonUserIdentityName] VARCHAR(75) NULL,
	[ApplicationPath] VARCHAR(500) NULL,
	[RequestUrl] VARCHAR(1000) NULL,
	[UserAgent] VARCHAR(1000) NULL,
	[AppMemEstimatedCPUTime] VARCHAR(10) NULL,
	[AppMemEstimatedMemoryUsage] VARCHAR(10) NULL,
	[AppMemRequestsInAppQueue] VARCHAR(10) NULL,
	[SvrMemCPUUsage] VARCHAR(10) NULL,
	[SvrMemAvailableMemory] VARCHAR(10) NULL,
	[SvrMemAppPoolCPUUsage] VARCHAR(10) NULL,
	[SvrMemAppPoolMemoryUsage] VARCHAR(10) NULL,
	[SyncID] UNIQUEIDENTIFIER NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
	[IsLoggedFromMsmq] BIT NOT NULL DEFAULT 0,
    [LogDateTime] DATETIME NOT NULL
)
